image: Visual Studio 2017

environment:
  sonar_token:
    secure: 4M8z89LHqy9Rho8Mi4i7V0Ajz/7kvDYolVFH2V0GjK5VO5dseuv2Dja/qmKbio1I
  github_auth_token:
    secure: XUib5rF8Uxwk7S2umtsFEQ9t5G0p/J3G3PNpWLZuNIyw/zNufLDCge8C6QJRTzQw

init:
- choco install opencover.portable
- choco install codecov
- choco install "msbuild-sonarqube-runner" -y

before_build:
- nuget restore
- ps: >- 
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER) {
        MSBuild.SonarQube.Runner.exe begin /k:"manuc66:JsonSubtypes" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.organization=manuc66-github" /d:"sonar.login=$env:sonar_token" /d:sonar.cs.opencover.reportsPaths=".\MyProject_coverage.xml" /d:sonar.cs.nunit.reportsPaths="nunitTestResult.xml" /d:"sonar.cpd.exclusions=**/*Tests.cs" /d:"sonar.language=cs" /d:"sonar.analysis.mode=preview" /d:"sonar.github.pullRequest=$env:APPVEYOR_PULL_REQUEST_NUMBER" /d:"sonar.github.repository=$env:APPVEYOR_REPO_NAME" /d:"sonar.github.oauth=$env:github_auth_token" 
    }
    elseif ($env:APPVEYOR_REPO_BRANCH -eq "master") {
        MSBuild.SonarQube.Runner.exe begin /k:"manuc66:JsonSubtypes" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.organization=manuc66-github" /d:"sonar.login=$env:sonar_token" /d:sonar.cs.opencover.reportsPaths=".\MyProject_coverage.xml" /d:sonar.cs.nunit.reportsPaths="nunitTestResult.xml" /d:"sonar.cpd.exclusions=**/*Tests.cs"  /d:"sonar.language=cs"
    }
    else {
        MSBuild.SonarQube.Runner.exe begin /k:"manuc66:JsonSubtypes" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.organization=manuc66-github" /d:"sonar.login=$env:sonar_token" /d:"sonar.branch.name=$env:APPVEYOR_REPO_BRANCH" /d:"sonar.branch.target=master" /d:sonar.cs.opencover.reportsPaths=".\MyProject_coverage.xml" /d:sonar.cs.nunit.reportsPaths="nunitTestResult.xml" /d:"sonar.cpd.exclusions=**/*Tests.cs"  /d:"sonar.language=cs"
    }

configuration: Release

nuget:  
  disable_publish_on_pr: true

build: 
  project: JsonSubTypes.sln
  verbosity: minimal

test_script:
- dir JsonSubTypes\bin\Release
- dir JsonSubTypes.Tests\bin\Release
- OpenCover.Console.exe -register:user -target:"nunit3-console.exe" -targetargs:".\JsonSubTypes.Tests\bin\Release\JsonSubTypes.Tests.dll --result:nunitTestResult.xml" -filter:"+[JsonSubTypes*]* -[JsonSubTypes.Tests]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"

after_test:
- ps: MSBuild.SonarQube.Runner.exe end /d:"sonar.login=$env:sonar_token"

artifacts:
  # pushing all *.nupkg files in build directory recursively
- path: 'JsonSubTypes\**\*.nupkg'

deploy:
- provider: NuGet
  name: NuGet
  server: https://www.nuget.org/api/v2/package
  api_key:
    secure: cSqsPd3H3eNIKcAiatmQXXe1oEqXANMUxS+5I4zvVqGR3k/ae8a/TaIvDuf8xJei
  artifact: /JsonSubTypes.*\.nupkg/
  on:
    branch: master
